name: Mirror and run GitLab CI

on:
  push: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: Gallium70/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.tsinghua.edu.cn/os-lab/2023s/ta/ucore-tutorial-checker-2023s"
      env:
        GITLAB_HOSTNAME: "git.tsinghua.edu.cn"
        GITLAB_PROJECT_ID: "20792"
        GITLAB_PROJECT_NAME: "ucore-tutorial-checker-2023"
        GITLAB_PROJECT_TOKEN: ${{secrets.GITLAB_PROJECT_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
